/**
 * Portuguese texting slang and informal abbreviations
 * Covers both Brazilian Portuguese (pt-BR) and European Portuguese (pt-PT)
 *
 * Contains:
 * - Greetings & Farewells
 * - Portuguese-specific phrases (disambiguation)
 * - Common abbreviations
 * - Questions & Responses
 * - Pronouns & Common words
 * - Common verbs & phrases
 * - Emotions & Reactions
 * - Laughing
 * - Brazilian slang
 * - Brazilian expressions
 * - European Portuguese slang
 * - Time expressions
 * - Common phrases
 * - Customer service
 * - Tech/Internet
 *
 * Total terms: ~500+
 */

const PORTUGUESE_SLANG = new Set([
   // === Greetings & Farewells ===
   'oi',
   'oii',
   'oiii',
   'ola',
   'olá',
   'olaa',
   'eai',
   'e ai',
   'e aí',
   'e ai mano',
   'fala',
   'falaa',
   'falaaa',
   'salve',
   'salvee',
   'bom dia',
   'bom dia amigo',
   'boa tarde',
   'boa noite',
   'boa noite ate amanha',
   'tchau',
   'tchauu',
   'tchauuu',
   'xau',
   'xauu',
   'flw',
   'flww',
   'falou',
   'falouu',
   'ate mais',
   'ate logo',
   'ate logo a gente se ve',
   'a gente se ve',
   'a gente se fala',
   'ate amanha',
   'abraco',
   'abracos',
   'beijo',
   'beijos',
   'bjs',
   'bjss',
   'bjao',
   'oi pessoal',

   // === Portuguese-specific phrases (disambiguation) ===
   'vamos comer alguma coisa',
   'alguma coisa',
   'te espero na entrada',
   'na entrada',
   'minha irma',
   'minha irma vem',
   'vem nos visitar',
   'proximo fim de semana',
   'a que horas voce sai',
   'voce sai do trabalho',
   'quanto custa a passagem',
   'passagem de aviao',
   'como eu posso chegar',
   'na sua casa',
   'tb vou',
   'dps a gente se fala',
   'blz vamos',
   'que maravilha',
   'que surpresa',
   'que raiva',
   'que alivio',
   'preciso falar com um atendente',
   'um atendente',
   'tenho um problema com meu pedido',
   'meu pedido',
   'quero cancelar minha assinatura',
   'minha assinatura',
   'meu pacote nao chegou',
   'meu pacote',
   'nao chegou',
   'quero um reembolso',
   'reembolso',
   'quando meu pedido chega',
   'pedido chega',
   'o produto chegou danificado',
   'chegou danificado',
   'tudo bem pode ser',
   'pode ser',
   'ok sem problema',
   'sem problema',
   'fechado',
   'de jeito nenhum',
   'jeito nenhum',
   'nem pensar',
   'nunca na vida',
   'de forma alguma',
   'forma alguma',
   'esta frio la fora',
   'la fora',
   'que dia lindo',
   'dia lindo',
   'tenho uma reuniao ao meio dia',
   'ao meio dia',
   'o prazo e sexta feira',
   'sexta feira',
   'terminei o projeto',
   'o projeto',
   'amanha preciso trabalhar',
   'preciso trabalhar',
   'as aulas comecam',
   'comecam as oito',
   'uma mesa para dois por favor',
   'para dois', // Portuguese - uses 'dois' not 'dos'
   'dois', // two (Portuguese)
   'a conta por favor',
   'estava delicioso obrigado',
   'delicioso obrigado',
   'o que voce quer comer',
   'quer comer',
   'vamos pedir uma pizza',
   'pedir uma pizza',
   'quero um cafe',
   'um cafe',
   'quero um sorvete',
   'um sorvete',
   'onde fica o aeroporto',
   'fica o aeroporto',
   'preciso reservar um hotel',
   'reservar um hotel',
   'como eu chego no centro',
   'chego no centro',
   'a que horas sai o trem',
   'sai o trem',
   'perdi meu voo',
   'meu voo',
   'te espero na entrada', // I wait for you at the entrance (Portuguese - uses 'na')
   'te espero na', // I wait for you at (Portuguese - uses 'na')
   'te espero', // I wait for you
   'espero na entrada', // wait at the entrance
   'espero na', // wait at (Portuguese - uses 'na')
   'espero', // I wait (also in Portuguese)
   'na entrada', // at the entrance (Portuguese - uses 'na')
   'ufa que alivio', // phew what a relief (Portuguese specific - uses 'ufa')
   'ufa', // phew (Portuguese specific)
   'nunca na vida', // never in life (Portuguese - uses 'na')
   'na vida', // in life (Portuguese - uses 'na')
   'na', // Portuguese contraction (em + a)

   // === Common abbreviations ===
   'vc',
   'vcs',
   'voce',
   'você',
   'tb',
   'tbm',
   'tambem',
   'também',
   'pq',
   'pqp',
   'porque',
   'por que',
   'porq',
   'cmg',
   'comigo',
   'ctg',
   'contigo',
   'ngm',
   'ninguem',
   'ninguém',
   'qnd',
   'quando',
   'qnt',
   'quanto',
   'qto',
   'mto',
   'muito',
   'mt',
   'mtt',
   'nd',
   'nada',
   'td',
   'tudo',
   'tdm',
   'agr',
   'agora',
   'hj',
   'hoje',
   'amanh',
   'amanha',
   'amanhã',
   'ontem',
   'dps',
   'depois',
   'blz',
   'beleza',
   'vlw',
   'valeu',
   'tmj',
   'tamo junto',
   'obg',
   'obgd',
   'obrigado',
   'obrigada',

   // === Questions & Responses ===
   'oq',
   'o que',
   'o quê',
   'cade',
   'cadê',
   'onde',
   'como',
   'quando',
   'quem',
   'qual',
   'quanto',
   'como assim',
   'serio',
   'sério',
   'jura',
   'verdade',
   'mesmo',
   'ta bom',
   'tá bom',

   // === Pronouns & Common words ===
   'eu',
   'tu',
   'ele',
   'ela',
   'nos',
   'nós',
   'eles',
   'elas',
   'voces',
   'vocês',
   'isso',
   'aquilo',
   'este',
   'esta',
   'esse',
   'essa',
   'estou',
   'esta',
   'estamos',
   'tenho',
   'tem',
   'temos',
   'com',
   'sem',
   'em',
   'para',
   'pra',
   'pro',
   'entre',
   'mas',
   'porem',
   'porém',
   'entao',
   'então',

   // === Common verbs & phrases ===
   'ta',
   'tá',
   'to',
   'tô',
   'ta bem',
   'tá bem',
   'ta bom',
   'tá bom',
   'ta certo',
   'pode ser',
   'pode crer',
   'claro',
   'claroo',
   'sim',
   'simm',
   'nao',
   'não',
   'naoo',
   'obrigado',
   'obrigada',
   'de nada',
   'por nada',
   'desculpa',
   'desculpaa',
   'perdao',
   'perdão',
   'perfeito',
   'otimo',
   'ótimo',
   'maravilhoso',
   'incrivel',
   'incrível',

   // === Emotions & Reactions ===
   'nossa',
   'nossaa',
   'caramba',
   'caraca',
   'caracaa',
   'putz',
   'putzz',
   'eita',
   'eitaa',
   'uau',
   'uauu',
   'legal',
   'legall',
   'massa',
   'massaa',
   'top',
   'topp',
   'show',
   'showw',
   'dahora',
   'demais',
   'demaiss',
   'maneiro',
   'maneiroo',
   'irado',
   'foda',
   'fodaa',
   'medo',
   'que medo',
   'que susto',
   'ai meu deus',
   'meu deus',

   // === Laughing ===
   'kk',
   'kkk',
   'kkkk',
   'kkkkk',
   'kkkkkk',
   'kkkkkkk',
   'rs',
   'rsrs',
   'rsrsrs',
   'haha',
   'hahaha',
   'ahahah',

   // === Brazilian slang ===
   'mano',
   'manoo',
   'manooo',
   'cara',
   'caraa',
   'brother',
   'bro',
   'parceiro',
   'parsa',
   'parsaa',
   'veio',
   'veioo',
   'velho',
   'bicho',
   'bichoo',
   'mina',
   'minaa',
   'gata',
   'gataa',
   'gato',
   'gatoo',
   'maluco',
   'malucoo',
   'doido',
   'doidoo',

   // === Brazilian expressions ===
   'po',
   'poo',
   'poxa',
   'poxaa',
   'tipo',
   'tipoo',
   'sei la',
   'sei lá',
   'ne',
   'né',
   'neh',
   'sabe',
   'entende',
   'sacou',
   'sacouu',
   'ligado',
   'ligadoo',
   'firmeza',
   'firmezaa',
   'suave',
   'suavee',
   'tranquilo',
   'tranquiloo',
   'de boa',
   'de boaa',
   'na moral',
   'na moralzinha',
   'bora',
   'boraa',
   'boraaa',
   'partiu',
   'partiuu',

   // === European Portuguese slang ===
   'fixe',
   'fixee',
   'giro',
   'giroo',
   'porreiro',
   'porreiroo',
   'bacano',
   'bacanoo',
   'gajo',
   'gajoo',
   'gaja',
   'gajaa',
   'miudo',
   'miuda',
   'bue',
   'bué',
   'yah',
   'ya',
   'tas',
   'tas bem',
   'tou',
   'tou bem',
   'cena',
   'cenaa',
   'curte',
   'curtir',
   'curti',

   // === Time expressions ===
   'agora',
   'logo',
   'depois',
   'antes',
   'hoje',
   'amanha',
   'ontem',
   'semana',
   'mes',
   'ano',
   'ja',
   'já',
   'jaja',
   'já já',
   'rapidinho',
   'rapidao',

   // === Common phrases ===
   'como voce esta',
   'como você está',
   'tudo bem',
   'tudo bom',
   'tudo certo',
   'tudo ok',
   'nao sei',
   'não sei',
   'eu sei',
   'eu acho',
   'acho que',
   'gosto muito',
   'te amo',
   'te adoro',
   'saudades',
   'saudade',
   'que saudade',
   'bom dia',
   'boa tarde',
   'boa noite',
   'boa sorte',
   'parabens',
   'parabéns',
   'feliz aniversario',
   'feliz aniversário',

   // === Customer service ===
   'preciso de ajuda',
   'pode me ajudar',
   'quero cancelar',
   'meu pedido',
   'minha compra',
   'nao chegou',
   'não chegou',
   'reembolso',
   'devolucao',
   'devolução',

   // === Tech/Internet ===
   'zap',
   'zapp',
   'zapzap',
   'insta',
   'face',
   'post',
   'foto',
   'video',
   'vídeo',
   'link',
   'site',
   'app',
   'baixar',
   'download',
]);

export default PORTUGUESE_SLANG;
