/**
 * German Slang Dictionary
 *
 * Contains German texting slang, abbreviations, and informal language patterns.
 * Includes standard German, Austrian German, Swiss German, and youth slang.
 *
 * Categories:
 * - Standard German expressions
 * - Texting abbreviations (SMS/Chat)
 * - Youth slang (Jugendsprache)
 * - Regional variants (Austrian, Swiss)
 * - Internet/Gaming slang
 * - Common greetings and farewells
 * - Exclamations and interjections
 *
 * Total terms: ~400+
 */

const GERMAN_SLANG = new Set([
   // ==========================================
   // GREETINGS & FAREWELLS
   // ==========================================
   'hallo',
   'hi',
   'hey',
   'moin',
   'moin moin',
   'servus',
   'grüß gott',
   'grüß dich',
   'guten tag',
   'guten morgen',
   'guten abend',
   'gute nacht',
   'na',
   'na du',
   'was geht',
   'was geht ab',
   'wie gehts',
   'wie geht es dir',
   'alles klar',
   'alles gut',
   'tschüss',
   'tschau',
   'ciao',
   'bis dann',
   'bis später',
   'bis bald',
   'bis morgen',
   "mach's gut",
   'machs gut',
   'hdl',
   'hdgdl',
   'hab dich lieb',
   'hab dich ganz doll lieb',
   'auf wiedersehen',
   'pfiat di',
   'pfüati',
   'ade',
   'adieu',
   'grüezi',
   'sali',
   'hoi',

   // ==========================================
   // TEXTING ABBREVIATIONS
   // ==========================================
   'lg',
   'liebe grüße',
   'mfg',
   'mit freundlichen grüßen',
   'vg',
   'viele grüße',
   'glg',
   'ganz liebe grüße',
   'bb',
   'bis bald',
   'bd',
   'bis dann',
   'bs',
   'bis später',
   'gn8',
   'gute nacht',
   'n8',
   'nacht',
   'wg',
   'wegen',
   'gg',
   'gegen',
   'zb',
   'zum beispiel',
   'dh',
   'das heißt',
   'bzw',
   'beziehungsweise',
   'usw',
   'und so weiter',
   'vllt',
   'vielleicht',
   'evtl',
   'eventuell',
   'eigtl',
   'eigentlich',
   'bzgl',
   'bezüglich',
   'jmd',
   'jemand',
   'etw',
   'etwas',
   'ggf',
   'gegebenenfalls',
   'inkl',
   'inklusive',
   'ca',
   'circa',
   'iwie',
   'irgendwie',
   'iwann',
   'irgendwann',
   'iwo',
   'irgendwo',
   'iwas',
   'irgendwas',
   'iwer',
   'irgendwer',
   'ka',
   'keine ahnung',
   'kA',
   'kp',
   'kein plan',
   'kb',
   'kein bock',
   'kd',
   'kein ding',
   'np',
   'kein problem',
   'thx',
   'danke',
   'pls',
   'bitte',
   'plz',
   'sry',
   'sorry',
   'omg',
   'oh mein gott',
   'wtf',
   'was zur hölle',
   'haha',
   'rofl',
   'xd',
   'xD',
   'jk',
   'nur spaß',
   'fyi',
   'zu deiner info',
   'afaik',
   'asap',
   'so schnell wie möglich',
   'imo',
   'meiner meinung nach',
   'imho',
   'btw',
   'übrigens',
   'aka',
   'auch bekannt als',
   'irl',
   'im echten leben',
   'brb',
   'bin gleich zurück',
   'afk',
   'weg vom rechner',
   'cu',
   'see you',
   'cya',
   'w8',
   'warte',
   'g2g',
   'muss los',
   'gtg',

   // ==========================================
   // DISAMBIGUATION (German specific)
   // ==========================================
   'ja genau',
   'ja klar',
   'ja gut',
   'ja okay',
   'ja sicher',
   'ja natürlich',

   // ==========================================
   // COMMON WORDS & EXPRESSIONS
   // ==========================================
   'ja',
   'nein',
   'nee',
   'ne',
   'jo',
   'joa',
   'jap',
   'jep',
   'nö',
   'nope',
   'ach so',
   'achso',
   'aha',
   'oho',
   'oje',
   'oh je',
   'mensch',
   'mann',
   'alter',
   'ey',
   'hey',
   'boah',
   'krass',
   'geil',
   'mega',
   'mega geil',
   'hammer',
   'hammermäßig',
   'stark',
   'super',
   'toll',
   'prima',
   'klasse',
   'spitze',
   'genial',
   'fantastisch',
   'wunderbar',
   'cool',
   'nice',
   'läuft',
   'läuft bei dir',
   'passt',
   'passt schon',
   'geht klar',
   'klar',
   'logo',
   'logisch',
   'kein thema',
   'null problemo',
   'easy',
   'eazy',
   'chillig',
   'entspannt',
   'locker',
   'geschenkt',
   'sicher',
   'bestimmt',
   'absolut',
   'definitiv',
   'auf jeden',
   'auf jeden fall',
   'aufjedenfall',
   'natürlich',
   'klar doch',
   'genau',
   'richtig',
   'stimmt',
   'eben',
   'halt',
   'schon',
   'doch',
   'wohl',
   'mal',
   'quasi',
   'sozusagen',
   'praktisch',
   'irgendwie',
   'voll',
   'total',
   'echt',
   'wirklich',
   'tatsächlich',
   'übrigens',
   'jedenfalls',
   'sowieso',
   'trotzdem',
   'obwohl',
   'allerdings',
   'jedoch',
   'deshalb',
   'deswegen',
   'darum',
   'daher',

   // ==========================================
   // YOUTH SLANG (Jugendsprache)
   // ==========================================
   'chill mal',
   'das ist lit',
   'gömmer go esse',
   'digga',
   'digger',
   'alter',
   'bruder',
   'bro',
   'brudi',
   'sis',
   'schwesti',
   'kumpel',
   'kollege',
   'dude',
   'typ',
   'kerl',
   'mädel',
   'tussi',
   'schnitte',
   'babo',
   'boss',
   'chef',
   'king',
   'queen',
   'pro',
   'noob',
   'nerd',
   'geek',
   'freak',
   'penner',
   'loser',
   'opfer',
   'lauch',
   'ehrenmann',
   'ehrenfrau',
   'ehrenlos',
   'lost',
   'fly',
   'lit',
   'safe',
   'real talk',
   'facts',
   'cringe',
   'sus',
   'sus af',
   'slay',
   'flex',
   'drip',
   'swag',
   'yolo',
   'sheesh',
   'sheeesh',
   'chillen',
   'abhängen',
   'gammeln',
   'zocken',
   'gamen',
   'streamen',
   'chatten',
   'texten',
   'liken',
   'posten',
   'sharen',
   'followen',
   'blocken',
   'ghosten',
   'simpen',
   'hypen',
   'flexen',
   'feiern',
   'abfeiern',
   'abgehen',
   'eskalieren',
   'ballern',
   'raffen',
   'checken',
   'peilen',
   'schnallen',
   'kapieren',
   'verstehen',
   'null plan',
   'keinen plan',
   'kein schimmer',
   'keine ahnung',
   'was laberst du',
   'labern',
   'quatschen',
   'reden',
   'snacken',
   'futtern',
   'mampfen',
   'pennen',
   'ratzen',
   'schlafen',
   'abhacken',
   'chillen',

   // ==========================================
   // EXCLAMATIONS & REACTIONS
   // ==========================================
   'wow',
   'whoa',
   'oha',
   'ohoh',
   'ups',
   'oops',
   'hoppla',
   'mist',
   'verdammt',
   'verflixt',
   'so ein mist',
   'scheiße',
   'scheisse',
   'kacke',
   'merde',
   'fuck',
   'shit',
   'crap',
   'damn',
   'gott sei dank',
   'zum glück',
   'endlich',
   'wahnsinn',
   'irre',
   'verrückt',
   'der hammer',
   'nicht wahr',
   'oder',
   'gell',
   'ne',
   'wa',
   'nich',
   'nicht',
   'gar nicht',
   'überhaupt nicht',
   'niemals',
   'nie',
   'immer',
   'manchmal',
   'oft',
   'selten',
   'endlich',
   'sofort',
   'gleich',
   'jetzt',
   'später',
   'morgen',
   'gestern',
   'heute',
   'bald',
   'langsam',
   'schnell',
   'hurtig',

   // ==========================================
   // QUESTIONS & RESPONSES
   // ==========================================
   'was',
   'wer',
   'wo',
   'wann',
   'warum',
   'wieso',
   'weshalb',
   'wie',
   'wie bitte',
   'wie denn',
   'was denn',
   'echt jetzt',
   'wirklich',
   'im ernst',
   'no way',
   'niemals',
   'und wie',
   'und ob',
   'na klar',
   'selbstverständlich',
   'versteht sich',
   'keine frage',
   'ohne frage',
   'zweifellos',
   'fraglos',
   'unbedingt',
   'sicher doch',
   'klaro',
   'oki',
   'okidoki',
   'alles roger',
   'roger',
   'verstanden',
   'gecheckt',
   'gerafft',
   'kapiert',
   'okay',
   'ok',
   'gut',
   'in ordnung',
   'einverstanden',
   'abgemacht',
   'deal',
   'gebongt',
   'geht klar',
   'machen wir',
   'wird gemacht',
   'erledigt',
   'fertig',
   'done',

   // ==========================================
   // AUSTRIAN GERMAN
   // ==========================================
   'griaß di',
   'griaß euch',
   'pfiat di',
   'baba',
   'leiwand',
   'ur leiwand',
   'ur geil',
   'oag',
   'oarg',
   'fesch',
   'gschert',
   'gspusi',
   'hawara',
   'oida',
   'geh bitte',
   'na geh',
   'jo eh',
   'passt scho',
   'wurscht',
   'wuascht',
   'is ma wurscht',
   'des is ma wurscht',
   'gfrei mi',
   'i gfrei mi',
   'owa',
   'na',
   'heast',
   'schau',
   'schau ma',
   'geh ma',
   'samma',
   'san ma',
   'wos',
   'wos is',
   'nix',
   'a bissl',
   'a bisserl',
   'a weng',
   'eh klar',
   'sowieso',
   'freilich',

   // ==========================================
   // SWISS GERMAN
   // ==========================================
   'grüezi',
   'grüessech',
   'sali',
   'salü',
   'hoi zäme',
   'tschau zäme',
   'uf widerluege',
   'adie',
   'merci',
   'merci vielmal',
   'danke vielmal',
   'bitte schön',
   'gern geschehen',
   'de nada',
   'genau so',
   'ebe',
   'äbe',
   'gäll',
   'oder',
   'nöd',
   'ned',
   'nüd',
   'nid',
   'chli',
   'chömed',
   'gömmer',
   'lönd',
   'lueg',
   'luege',
   'mega',
   'voll',
   'huere',
   'huere geil',
   'lässig',
   'easy',
   'gopf',
   'gopferdami',
   'gopferteckel',
   'cheib',
   'cheibe',
   'siech',

   // ==========================================
   // COMMON PHRASES (Chat/Text style)
   // ==========================================
   'was machst du',
   'was machst du so',
   'was geht bei dir',
   'alles fit',
   'wie siehts aus',
   'wie sieht es aus',
   'hast du zeit',
   'hast du bock',
   'ich hab bock',
   'kein bock',
   'keine lust',
   'ich hab keine lust',
   'ich hab keinen bock',
   'komm vorbei',
   'kommst du mit',
   'gehst du mit',
   'wann kommst du',
   'wo bist du',
   'bin da',
   'bin unterwegs',
   'komme gleich',
   'dauert noch',
   'bin spät dran',
   'warte mal',
   'moment mal',
   'eine sekunde',
   'kurz warten',
   'muss los',
   'ich muss weg',
   'muss arbeiten',
   'hab zu tun',
   'bin beschäftigt',
   'ruf dich an',
   'ruf mich an',
   'schreib mir',
   'melde dich',
   'lass hören',
   'sag bescheid',
   'gib bescheid',
   'kein stress',
   'mach dir keine sorgen',
   'alles wird gut',
   'wird schon',
   'schaffen wir',
   'klappt schon',
   'egal',
   'mir egal',
   'ist mir egal',
   'mir doch egal',
   'wayne',
   'ist doch wayne',
   'wen juckts',
   'ich liebe dich',
   'ich mag dich',
   'du bist toll',
   'du bist der beste',
   'du bist die beste',
   'danke dir',
   'vielen dank',
   'danke schön',
   'dankeschön',
   'bitte schön',
   'bitteschön',
   'gern geschehen',
   'nichts zu danken',
   'kein problem',
   'keine ursache',
   'tut mir leid',
   'entschuldigung',
   'verzeihung',
   'sorry dafür',
   'mein fehler',
   'war mein fehler',
   'ich habs verbockt',
   'prost',
   'zum wohl',
   'guten appetit',
   'mahlzeit',
   'gesundheit',
   'alles gute',
   'herzlichen glückwunsch',
   'glückwunsch',
   'gratuliere',
   'viel erfolg',
   'viel glück',
   'viel spaß',
   'gute besserung',
   'gute reise',
   'schönen tag noch',
   'schönes wochenende',
   'schönen feierabend',
]);

module.exports = GERMAN_SLANG;
