/**
 * Italian texting slang and informal abbreviations
 *
 * Contains:
 * - Greetings & Farewells
 * - Very common Italian words (disambiguation)
 * - Italian-specific expressions
 * - Common abbreviations
 * - Questions & Responses
 * - Pronouns & Common words
 * - Common verbs & phrases
 * - Affirmatives & Negatives
 * - Emotions & Reactions
 * - Laughing & Reactions
 * - Time expressions
 * - Informal expressions
 * - Slang & Youth expressions
 * - Regional expressions
 * - Food & Social
 * - Common phrases
 *
 * Total terms: ~350+
 */

const ITALIAN_SLANG = new Set([
   // === Greetings & Farewells ===
   'ciao',
   'ciaoo',
   'ciaooo',
   'ciaoooo',
   'salve',
   'buongiorno',
   'buonasera',
   'buonanotte',
   'arrivederci',
   'ti aspetto', // I wait for you
   'ti aspetto all ingresso', // I wait for you at the entrance (without apostrophe)
   'all ingresso', // all'ingresso (without apostrophe)
   'addio',
   'a presto',
   'a dopo',
   'ci vediamo',
   'ci sentiamo',

   // === Very common Italian words (disambiguation) ===
   'bene',
   'molto',
   'sono',
   'stanco',
   'scusa',
   'prego',
   'grazie',
   'mille',
   'oggi',
   'domani',
   'ieri',
   'adesso',
   'subito',
   'anche',
   'perche',
   'perché',
   'quando',
   'dove',
   'cosa',
   'come',
   'chi',
   'quale',

   // === Italian-specific expressions ===
   'che figata',
   'che schifo',
   'che bello',
   'che bella',
   'che sorpresa',
   'che paura',
   'che sollievo',
   'che sfiga',
   'e un casino',
   'un casino',
   'dov e',
   'dov e l',
   'dov e l aeroporto',
   'l aeroporto',
   'aeroporto',
   'nessun problema',
   'ok nessun problema',
   'nessun',
   'non se ne parla',
   'se ne parla',
   'xke',

   // === Common abbreviations ===
   'cmq',
   'comunque',
   'xche',
   'xké',
   'perche',
   'perché',
   'nn',
   'non',
   'sn',
   'sono',
   'ke',
   'che',
   'x',
   'per',
   'xo',
   'però',
   'qnd',
   'quando',
   'qnt',
   'quanto',
   'qlc',
   'qualcosa',
   'qlcn',
   'qualcuno',
   'tt',
   'tutto',
   'ttp',
   'ti voglio bene',
   'tvb',
   'tvtb',
   'ti voglio tanto bene',

   // === Questions & Responses ===
   'cosa',
   'come',
   'dove',
   'quando',
   'chi',
   'quale',
   'quanto',
   'perche',
   'come stai',
   'cm stai',
   'tutto bene',
   'tutto ok',
   'tutto a posto',

   // === Pronouns & Common words ===
   'io',
   'tu',
   'lui',
   'lei',
   'noi',
   'voi',
   'loro',
   'questo',
   'quello',
   'questa',
   'quella',
   'sono',
   'sei',
   'siamo',
   'siete',
   'ho',
   'hai',
   'ha',
   'abbiamo',
   'avete',
   'hanno',
   'con',
   'senza',
   'in',
   'su',
   'per',
   'tra',
   'fra',
   'ma',
   'pero',
   'quindi',
   'allora',
   'dunque',

   // === Common verbs & phrases ===
   'va bene',
   'vabbene',
   'vabbe',
   'vabbè',
   'ok va bene',
   'si certo',
   'certo',
   'certamente',
   'sicuro',
   'sicuramente',
   'grazie',
   'grz',
   'graz',
   'grazie mille',
   'prego',
   'scusa',
   'scusami',
   'mi dispiace',
   'perfetto',
   'fantastico',
   'bellissimo',
   'benissimo',

   // === Affirmatives & Negatives ===
   'si',
   'sì',
   'sisi',
   'sisisi',
   'no',
   'nono',
   'nonono',
   'niente',
   'nulla',
   'mai',
   'sempre',
   'forse',
   'magari',
   'assolutamente',

   // === Emotions & Reactions ===
   'bello',
   'bella',
   'bellissimo',
   'bellissima',
   'bravo',
   'brava',
   'forte',
   'fortissimo',
   'pazzesco',
   'incredibile',
   'fantastico',
   'meraviglioso',
   'terribile',
   'orribile',
   'che bello',
   'che forte',
   'che figata',
   'che schifo',
   'mamma mia',
   'madonna',
   'oddio',
   'oh dio',
   'cavolo',
   'caspita',
   'accidenti',
   'porca miseria',

   // === Laughing & Reactions ===
   'ahah',
   'ahaha',
   'ahahah',
   'ahahahah',
   'haha',
   'hahaha',
   'lol',
   'ahahahahah',

   // === Time expressions ===
   'adesso',
   'ora',
   'dopo',
   'prima',
   'oggi',
   'domani',
   'ieri',
   'stasera',
   'stanotte',
   'stamattina',
   'pomeriggio',
   'settimana',
   'mese',
   'anno',
   'subito',
   'presto',
   'tardi',

   // === Informal expressions ===
   'boh',
   'mah',
   'eh',
   'uffa',
   'basta',
   'dai',
   'daii',
   'daiii',
   'forza',
   'andiamo',
   'vamos',
   'aspetta',
   'aspè',
   'senti',
   'guarda',
   'vedi',
   'ecco',
   'appunto',
   'esatto',
   'giusto',

   // === Slang & Youth expressions ===
   'figo',
   'figa',
   'fichissimo',
   'fico',
   'ganzo',
   'sballo',
   'sballato',
   'mitico',
   'mega',
   'super',
   'top',
   'troppo forte',
   'una cifra',
   'un casino',
   'un sacco',
   'un botto',
   'alla grande',
   'alla fine',
   'tipo',
   'cioe',
   'cioè',
   'praticamente',
   'insomma',

   // === Regional expressions ===
   'daje',
   'aò',
   'ao',
   'anvedi',
   'ammazza',
   'uè',
   'ue',
   'minchia',
   'belin',
   'cribbio',

   // === Food & Social ===
   'mangiamo',
   'pranzo',
   'cena',
   'colazione',
   'aperitivo',
   'caffè',
   'caffe',
   'pizza',
   'pasta',
   'gelato',
   'birra',
   'vino',

   // === Common phrases ===
   'che cosa',
   'cosa fai',
   'cosa c è',
   'cosa ce',
   'come va',
   'come stai',
   'tutto bene',
   'sto bene',
   'non lo so',
   'non so',
   'lo so',
   'mi piace',
   'ti amo',
   'ti voglio bene',
   'a domani',
   'a dopo',
   'buona giornata',
   'buona serata',
   'in bocca al lupo',
   'crepi',
]);

export default ITALIAN_SLANG;
