/**
 * Dutch Slang Dictionary
 *
 * Contains Dutch texting slang, abbreviations, and informal language patterns.
 * Includes standard Dutch (Netherlands) and Belgian Dutch (Flemish) variants.
 *
 * Categories:
 * - Standard Dutch expressions
 * - Texting abbreviations (SMS/Chat)
 * - Youth slang (Jongerentaal)
 * - Regional variants (Flemish/Belgian Dutch)
 * - Internet/Gaming slang
 * - Common greetings and farewells
 * - Exclamations and interjections
 *
 * Total terms: ~300+
 */

const DUTCH_SLANG = new Set([
    // ==========================================
    // GREETINGS & FAREWELLS
    // ==========================================
    'hoi',
    'hallo',
    'hai',
    'hee',
    'heey',
    'heeey',
    'joehoe',
    'goedemorgen',
    'goedemiddag',
    'goedenavond',
    'goedenacht',
    'goeiendag',
    'goeiemiddag',
    'goeiemorgen',
    'doei',
    'doeg',
    'daag',
    'tot ziens',
    'tot later',
    'tot zo',
    'tot straks',
    'tot morgen',
    'tot snel',
    'tot gauw',
    'toedeloe',
    'toedeledokie',
    'aju',
    'ajuu',
    'ajuus',
    'ajuuus',

    // ==========================================
    // TEXTING ABBREVIATIONS
    // ==========================================
    'gr',
    'groeten',
    'mvg',
    'met vriendelijke groet',
    'vg',
    'vriendelijke groet',
    'lgg',
    'liefs en groetjes',
    'xx',
    'xoxo',
    'ff',
    'efkes',
    'efje',
    'idd',
    'inderdaad',
    'haha',
    'hihi',
    'hehe',
    'oke',
    'oké',
    'okidoki',
    'dankje',
    'bv',
    'bijvoorbeeld',
    'oa',
    'onder andere',
    'tov',
    'ten opzichte van',
    'ivm',
    'in verband met',
    'nav',
    'naar aanleiding van',
    'obv',
    'op basis van',
    'mbt',
    'met betrekking tot',
    'zgn',
    'zogenaamd',
    'ca',
    'circa',
    'ikr',
    'ik kom er aan',
    'wbb',
    'wees even bij',
    'tzt',
    'te zijner tijd',
    'sws',
    'sowieso',
    'owja',
    'oh ja',
    'owjee',
    'ojee',

    // ==========================================
    // COMMON WORDS & EXPRESSIONS
    // ==========================================
    'ja',
    'jaa',
    'jaaa',
    'nee',
    'neen',
    'neee',
    'joh',
    'jup',
    'jupp',
    'jepp',
    'jeuh',
    'nop',
    'tuurlijk',
    'natuurlijk',
    'zeker',
    'zeker weten',
    'absoluut',
    'precies',
    'klopt',
    'klopje',
    'snap ik',
    'begrijp ik',
    'logisch',
    'ofzo',
    'ofzoiets',
    'enzo',
    'enzovoort',
    'mwah',
    'mwa',
    'boeit',
    'maakt niet uit',
    'geeft niet',
    'ach',
    'och',
    'oei',
    'auw',
    'au',
    'wauw',
    'jeetje',
    'jemig',
    'jeminee',
    'gossie',
    'gossiemijne',
    'tjongejonge',
    'tjee',
    'goh',
    'goeie',
    'alsjeblieft',
    'alstublieft',
    'aub',
    'svp',
    'dankjewel',
    'dankuwel',
    'dank je',
    'dank u',
    'bedankt',
    'bedankje',
    'super bedankt',
    'heel erg bedankt',
    'graag gedaan',
    'geen probleem',
    'geen dank',
    'niets te danken',

    // ==========================================
    // YOUTH SLANG (Jongerentaal)
    // ==========================================
    'broer',
    'maat',
    'maatje',
    'vriend',
    'vriendje',
    'kerel',
    'gast',
    'gozer',
    'vent',
    'knul',
    'jongen',
    'meid',
    'meisje',
    'sukkel',
    'malloot',
    'oelewapper',
    'eikel',
    'lekker',
    'hartstikke lekker',
    'tof',
    'toffe',
    'gaaf',
    'gave',
    'vet',
    'vet gaaf',
    'vet tof',
    'gezellig',
    'supergezellig',
    'hartstikke gezellig',
    'kut',
    'kutdag',
    'klote',
    'godver',
    'potverdorie',
    'verdorie',
    'verdomme',
    'gadverdamme',
    'gatver',
    'bah',
    'jakkes',

    // ==========================================
    // DISAMBIGUATION (Dutch-specific)
    // ==========================================
    // Common Dutch function words and particles (distinct from German/French)
    'ook',
    'mee',
    'toch',
    'hoor',
    'zeg',
    'wel',
    'maar',
    'want',
    'gewoon',
    'eigenlijk',
    'morgen',
    'veel',
    'heel',
    'echt',
    'lekker',
    // Key Dutch phrases for slang override on ML-primary text
    'tot morgen',
    'tot morgen dan',
    'waar ben je nu',
    'kom je ook mee',
    'veel succes morgen',
    'hoe gaat het',
    'hoe gaat het met je',
    'hoe gaat ie',
    'gaat goed',
    'het gaat goed',
    'prima',
    'uitstekend',
    'goed',
    'niet slecht',
    'kan beter',
    'matig',
    'slecht',
    'beroerd',
    'moe',
    'druk',
    'blij',
    'trots',
    'jammer',
    'helaas',
    'helaas pindakaas',
    'wat jammer',
    'wat erg',
    'erg jammer',

    // ==========================================
    // QUESTIONS & RESPONSES
    // ==========================================
    'wat',
    'wie',
    'waar',
    'wanneer',
    'waarom',
    'waarvoor',
    'hoe',
    'welke',
    'welk',
    'hoe laat',
    'hoe ver',
    'hoe lang',
    'hoe veel',
    'hoeveel',
    'wat bedoel je',
    'echt waar',
    'meen je dat',
    'serieus',
    'echt',
    'watt',
    'huh',
    'he',
    'hee',
    'toch',
    'toch wel',
    'weet ik veel',
    'geen idee',
    'weet ik niet',
    'weet je niet',
    'misschien',
    'wellicht',
    'misschien wel',
    'weet nog niet',

    // ==========================================
    // COMMON PHRASES (Chat/Text style)
    // ==========================================
    'wat doe je',
    'wat ben je aan het doen',
    'waar ben je',
    'ben je thuis',
    'ben onderweg',
    'kom er aan',
    'ik ben er bijna',
    'even wachten',
    'wacht even',
    'momentje',
    'een seconde',
    'ik bel je',
    'stuur me een berichtje',
    'app me',
    'whatsapp me',
    'heb je tijd',
    'wanneer ben je vrij',
    'zullen we afspreken',
    'ga je mee',
    'kom je ook',
    'doe je mee',
    'heb je zin',
    'ik heb er zin in',
    'geen zin',
    'ik ga',
    'ik moet gaan',
    'ik moet weg',
    'druk bezig',
    'later meer',
    'laat het weten',
    'geef een seintje',
    'ik hou van je',
    'ik mis je',
    'succes',
    'veel succes',
    'veel plezier',
    'geniet ervan',
    'fijne dag',
    'fijn weekend',
    'prettig weekend',
    'fijne vakantie',
    'beterschap',
    'gefeliciteerd',
    'proficiat',
    'van harte',
    'proost',
    'eet smakelijk',
    'smakelijk',

    // ==========================================
    // FLEMISH / BELGIAN DUTCH
    // ==========================================
    'allez',
    'allee',
    'awel',
    'amai',
    'amaai',
    'zever',
    'zeveren',
    'ge',
    'gij',
    'uw',
    'da',
    "da's",
    'da is',
    'ge kunt',
    'ge moet',
    'wa zegt ge',
    'wa doe je',
    'wa is er',
    'zeker weten',
    'zo is dat',
    'nie',
    'nie waar',
    'het en is nie',
    'goesting',
    'ik heb er goesting in',
    'proper',
    'schoon',
    'schoon bezig',
    'ambetant',
    'ambras',
    'plezant',
    'lastig',
    'moeilijk',
    'gemakkelijk',
    'efkes',
    'even',
    'straks',
    'dadelijk',
    'rap',
    'vlug',
]);

module.exports = DUTCH_SLANG;
