/**
 * French texting slang and informal abbreviations
 *
 * Contains:
 * - Greetings & Farewells
 * - Common abbreviations
 * - Common French phrases
 * - Questions & Responses
 * - Pronouns & Common words
 * - Common verbs & phrases
 * - Emotions & Reactions
 * - Time expressions
 * - Tech & Social Media
 * - Informal expressions
 * - Filler words
 *
 * Total terms: ~300+
 */

const FRENCH_SLANG = new Set([
   // === Disambiguation (French-specific phrases) ===
   'ou est laeroport',
   'ou est l aeroport',
   'laeroport',

   // === Greetings & Farewells ===
   'salut',
   'salut ca va', // hi how are you
   'salut ca va bien', // hi I'm good
   'ca va bien', // I'm good
   'slt',
   'sltt',
   'salu',
   'pas de probleme', // no problem
   'pas de souci', // no worries
   'je tattends', // je t'attends (without apostrophe)
   'je tattends a lentree', // I wait for you at the entrance
   'lentree', // l'entrée (without apostrophe)
   'coucou',
   'cc',
   'ckoi',
   'bjr',
   'bsr',
   'bonjour',
   'bonsoir',
   'bonne nuit',
   'bn',
   'a+',
   'a++',
   'a plus',
   'a bientot',
   'a toute',
   '@+',
   '@++',
   'bisou',
   'bisous',
   'biz',
   'bizz',
   'bsx',
   'bzou',
   'bzx',

   // === Common abbreviations ===
   'mdr',
   'mdrrr',
   'mdrr',
   'ptdr',
   'ptdrrr',
   'xptdr',
   'jsp',
   'jsais pas',
   'chais pas',
   'sais pas',
   'jcp',
   'chp',
   'jtm',
   'jet aime',
   'je taime',
   'tkt',
   'tinquiete',
   't inquiete',
   'tqt',
   'tinkiet',
   'jpeux pas',
   'jpp',
   'peux pas',
   'jsuis',
   'chuis',
   'je suis',
   'je suis fatigue',
   'je suis fatigué',
   'je suis content',
   'je suis la',
   'je suis là',
   'jespere',
   'jespere que',
   'jespere que tu vas bien',

   // === Common French phrases ===
   'grave',
   'grave bien',
   'cest grave',
   'cest grave bien',
   'grave bien le film',
   'slt jespere',
   'slt jespere que tu vas bien',
   'tu vas bien',
   'le film',
   'bien le film',
   'il fait froid',
   'il fait froid dehors',
   'il fait chaud',
   'il fait beau',
   'fait froid',
   'fait chaud',
   'dehors',
   'la date limite',
   'la date limite est',
   'la date limite est vendredi',
   'date limite',
   'date limite est vendredi',
   'est vendredi',
   'vendredi',
   'je dois reserver',
   'je dois reserver un hotel',
   'reserver un hotel',
   'un hotel',
   'jai rate',
   'jai rate mon vol',
   'rate mon vol',
   'mon vol',

   // === Questions & Responses ===
   'quoi',
   'koi',
   'kwa',
   'pourquoi',
   'pk',
   'pq',
   'pkoi',
   'comment',
   'cmt',
   'cmnt',
   'ou',
   'quand',
   'qd',
   'qui',
   'ki',
   'quest ce que',
   'keskon',
   'keske',
   'keski',
   'keskia',

   // === Pronouns & Common words ===
   'moi',
   'toi',
   'lui',
   'elle',
   'nous',
   'vous',
   'eux',
   'elles',
   'cest',
   'ct',
   'cetait',
   'ca',
   'sa',
   'ses',
   'cette',
   'ce',
   'tu',
   'je',
   'il',
   'on',
   'avec',
   'avc',
   'avk',
   'sans',
   'ss',
   'dans',
   'ds',
   'sur',
   'pour',
   'pr',
   'par',
   'mais',
   'ms',
   'donc',
   'dc',
   'alors',
   'alr',
   'sinon',
   'sinn',

   // === Common verbs & phrases ===
   'jai',
   'jai pas',
   'tas',
   'ta',
   'ta pas',
   'il y a',
   'ya',
   'yen a',
   'faut',
   'fo',
   'fallait',
   'falait',
   'cava',
   'ca va',
   'sava',
   'cv',
   'bien',
   'bn',
   'tres bien',
   'tb',
   'pas mal',
   'ouais',
   'oui',
   'wai',
   'wé',
   'we',
   'nan',
   'non',
   'bof',
   'dac',
   'dak',
   'dacord',
   'daccord',

   // === Emotions & Reactions ===
   'trop',
   'tro',
   'super',
   'genial',
   'cool',
   'grave',
   'grv',
   'ouf',
   'chanmé',
   'chanme',
   'mortel',
   'mortel de rire',
   'enorme',
   'dingue',
   'ohlala',
   'oh lala',
   'olala',
   'mince',
   'zut',
   'merde',
   'ptn',
   'putain',
   'oh mon dieu',

   // === Time expressions ===
   'maintenant',
   'mtn',
   'ajd',
   'aujourd hui',
   'aujourdhui',
   'hier',
   'demain',
   'dm',
   'ce soir',
   'csoir',
   'cette semaine',
   'la semaine prochaine',
   'plus tard',
   'tt',
   'toujours',
   'tjr',
   'tjrs',
   'jamais',
   'jms',
   'souvent',
   'svt',
   'parfois',
   'prf',
   'bientot',
   'btot',

   // === Tech & Social Media ===
   'texto',
   'sms',
   'tel',
   'telephone',
   'ordi',
   'ordinateur',
   'pc',
   'tel',
   'appli',
   'application',
   'photo',
   'pix',
   'video',
   'vid',
   'insta',
   'snap',
   'fb',
   'facebook',
   'whatsapp',
   'wp',

   // === Informal expressions ===
   'tranquille',
   'tranqu',
   'trankil',
   'oklm',
   'au calme',
   'peinard',
   'relax',
   'desolee',
   'desole',
   'dsl',
   'pardon',
   'pard',
   'merci',
   'mci',
   'merci bcp',
   'merci beaucoup',
   'stp',
   'sil te plait',
   'svp',
   'sil vous plait',

   // === Filler words ===
   'genre',
   'gnr',
   'en fait',
   'enfait',
   'enft',
   'bah',
   'ben',
   'euh',
   'hein',
   'quoi',
   'voila',
   'vla',
   'bref',
]);

export default FRENCH_SLANG;
